version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: dogbank-postgres
    environment:
      POSTGRES_DB: dogbank
      POSTGRES_USER: dogbank
      POSTGRES_PASSWORD: dog1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      
    networks:
      - dogbank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dogbank -d dogbank"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Banco Central Module (sem dependências)
  bancocentral-service:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.bancocentral
    container_name: bancocentral-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dogbank
      SPRING_DATASOURCE_USERNAME: dogbank
      SPRING_DATASOURCE_PASSWORD: dog1234
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dogbank-network
    restart: unless-stopped

  # Auth Module
  auth-service:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.auth
    container_name: auth-service
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dogbank
      SPRING_DATASOURCE_USERNAME: dogbank
      SPRING_DATASOURCE_PASSWORD: dog1234
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dogbank-network
    restart: unless-stopped

  # Account Module
  account-service:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.account
    container_name: account-service
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dogbank
      SPRING_DATASOURCE_USERNAME: dogbank
      SPRING_DATASOURCE_PASSWORD: dog1234
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy
      auth-service:
        condition: service_started
    networks:
      - dogbank-network
    restart: unless-stopped

  # Notification Module
  notification-service:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.notification
    container_name: notification-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dogbank
      SPRING_DATASOURCE_USERNAME: dogbank
      SPRING_DATASOURCE_PASSWORD: dog1234
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dogbank-network
    restart: unless-stopped

  # Integration Module
  integration-service:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.integration
    container_name: integration-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dogbank
      SPRING_DATASOURCE_USERNAME: dogbank
      SPRING_DATASOURCE_PASSWORD: dog1234
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dogbank-network
    restart: unless-stopped

  # Transaction Module (depende do bancocentral)
  transaction-service:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.transaction
    container_name: transaction-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dogbank
      SPRING_DATASOURCE_USERNAME: dogbank
      SPRING_DATASOURCE_PASSWORD: dog1234
      SPRING_PROFILES_ACTIVE: docker
      BANCOCENTRAL_API_URL: http://bancocentral-service:8085/api/bancocentral/pix/validate
    depends_on:
      postgres:
        condition: service_healthy
      bancocentral-service:
        condition: service_started
      account-service:
        condition: service_started
    networks:
      - dogbank-network
    restart: unless-stopped

  # Nginx como API Gateway (opcional)
  nginx:
    image: nginx:alpine
    container_name: dogbank-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - auth-service
      - account-service
      - transaction-service
      - bancocentral-service
      - integration-service
      - notification-service
    networks:
      - dogbank-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  dogbank-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

