apiVersion: v1
kind: Secret
metadata:
  name: dogbank-postgres-secret
  namespace: production
type: Opaque
data:
  # Valores em base64
  # dogbank -> ZG9nYmFuaw==
  # dog1234 -> ZG9nMTIzNA==
  POSTGRES_USER: ZG9nYmFuaw==
  POSTGRES_PASSWORD: ZG9nMTIzNA==
  POSTGRES_DB: ZG9nYmFuaw==