services:
  dogbank-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dogbank-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules