name: docker-publish
on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: auth
            context: ./dogbank
            dockerfile: ./dogbank/auth-module/Dockerfile
            image: schawirin/dogbank-auth-service
          - name: account
            context: ./dogbank
            dockerfile: ./dogbank/account-module/Dockerfile
            image: schawirin/dogbank-account-service
          - name: transactions
            context: ./dogbank
            dockerfile: ./dogbank/transaction-module/Dockerfile
            image: schawirin/dogbank-transaction-service
          - name: bancocentral
            context: ./dogbank
            dockerfile: ./dogbank/bancocentral-module/Dockerfile
            image: schawirin/dogbank-bancocentral-service
          - name: integration
            context: ./dogbank
            dockerfile: ./dogbank/integration-module/Dockerfile
            image: schawirin/dogbank-integration-service
          - name: notifications
            context: ./dogbank
            dockerfile: ./dogbank/notification-module/Dockerfile
            image: schawirin/dogbank-notification-service
          - name: frontend
            context: ./dogbank-frontend
            dockerfile: ./dogbank-frontend/Dockerfile
            image: schawirin/dogbank-frontend

    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Compute tags
        id: vars
        run: |
          SHA="${GITHUB_SHA::7}"
          echo "sha=${SHA}" >> $GITHUB_OUTPUT
      
      - name: Build & Push ${{ matrix.service.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          push: true
          platforms: linux/amd64
          tags: |
            ${{ matrix.service.image }}:latest
            ${{ matrix.service.image }}:${{ steps.vars.outputs.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max