name: quality-gate
on: [pull_request]
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Backend Java (JaCoCo)
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build & Test backend (JaCoCo)
        working-directory: ./dogbank
        run: mvn -B -q test jacoco:report

      # Frontend (opcional)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Test frontend with coverage (se existir)
        working-directory: ./dogbank-frontend
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ]; then npm ci; else npm install; fi
            npm test -- --coverage || true
          fi

      # Enviar cobertura
      - name: Upload Java coverage (JaCoCo XML)
        run: npx -y @datadog/datadog-ci@latest coverage upload --format=jacoco ./dogbank/target/site/jacoco/jacoco.xml
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_SITE: ${{ secrets.DD_SITE }}

      - name: Upload Frontend coverage (LCOV) se existir
        run: |
          if [ -f ./dogbank-frontend/coverage/lcov.info ]; then
            npx -y @datadog/datadog-ci@latest coverage upload --format=lcov ./dogbank-frontend/coverage/lcov.info
          fi
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_SITE: ${{ secrets.DD_SITE }}

      # Avaliar Quality Gates (falha PR se violar regra)
      - name: Evaluate Datadog Quality Gates
        run: npx -y @datadog/datadog-ci@latest gate evaluate --timeout 120 # opcional: --fail-on-empty
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          DD_SITE: ${{ secrets.DD_SITE }}
